export enum UserAction {
  REQUEST_HINT = 'REQUEST_HINT',
  NEXT_QUESTION = 'NEXT_QUESTION',
  SUBMIT_ANSWER_1 = 'SUBMIT_ANSWER_1',
  SUBMIT_ANSWER_2 = 'SUBMIT_ANSWER_2',
  SUBMIT_ANSWER_3 = 'SUBMIT_ANSWER_3',
  UNKNOWN = 'UNKNOWN'
}
